title: Kaoê Menna
lang: pt_br
description: >-
  Desenvolvedor Full Stack de aplicações mobile, web, embarcados e IoT.
twitter_username: KMMenna
github_username:  kmmenna
email: contato@kaoemenna.com.br

# Build settings
timezone: America/Sao_Paulo
encoding: utf-8
markdown: kramdown
theme: minima